name: 4AI Review Request
description: Request structured reviews from Claude, Gemini, Google AI Studio, ChatGPT
title: "4AI Review: EXITON SaaS Architecture"
labels: ["review","ai","architecture"]
body:
  - type: markdown
    attributes:
      value: |
        Target docs:
        - docs/EXITON_SaaS_上位構想書.md
        - docs/EXITON_SaaS_MasterPlan_EN.md
        - docs/review_prompt.md
  - type: textarea
    id: focus
    attributes:
      label: Focus
      description: e.g. "Minimum data integration points" or "Monetization"
      placeholder: What should AI focus on?
    validations:
      required: false
